HOST='localhost'
PORT=3000
DEBUG=True
SQLALCHEMY_DATABASE_URI='sqlite:///softwareEng.db'
SQLALCHEMY_TRACK_MODIFICATIONS=False
SECRET_KEY='importantly very secret key'
WTF_CSRF_ENABLED=True
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = 'softwarecastingflask@gmail.com'
MAIL_PASSWORD = 'casting34'
RECAPTCHA_PUBLIC_KEY = '6LeYIbsSAAAAACRPIllxA7wvXjIE411PfdB2gt2J'
RECAPTCHA_PRIVATE_KEY = '6LeYIbsSAAAAAJezaIq3Ft_hSTo0YtyeFG-JgRtu'
POST_LOGIN_URL = 'http://localhost:3000/login'
roleAdmin = 'Admin'
adminDescription = 'Admin is allowed add guest users or see the complete content.'
roleUser = 'Guest'
guestDescription = 'Guest is allowed to content in application.'
SECURITY_EMAIL_SALT = 'salt of email'
SECURITY_PASSWORD_SALT = 'salt of password'
